=== asrulhadi/dscsim/src/main/resources/etc/device.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://dscsim.sourcefore.net/xml/ns/dscsim"
	xmlns:dscsim="http://dscsim.sourcefore.net/xml/ns/dscsim"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:include schemaLocation="./screen-element-types.xsd" />

	<xsd:element name="device">
	 	<xsd:complexType>
	 		<xsd:sequence>
				<xsd:element name="screens" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="screen" type="dscsim:Screen" minOccurs="0" maxOccurs="unbounded"/>
							</xsd:sequence>				
					</xsd:complexType>
				</xsd:element>	 		
				
				<xsd:element name="actions" type="dscsim:Actions"  minOccurs="0"/>
			 		
				
	 		</xsd:sequence>
	 	</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="Screen">	
		<xsd:sequence>
			<xsd:element name="description" type="xsd:anySimpleType" minOccurs="0"/>
			<xsd:element name="fields" type="dscsim:Fields"  minOccurs="0" maxOccurs="unbounded"/>				
			<xsd:element name="actions" type="dscsim:Actions" minOccurs="0"/>				
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>			
		<xsd:attribute name="implementation" type="xsd:string" use="optional"/>	
		<xsd:attribute name="scope" default="transient">	
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="transient"/>
					<xsd:enumeration value="session"/>
					<xsd:enumeration value="persistant"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>	
	</xsd:complexType>
	
	<xsd:complexType name="Fields">
		<xsd:complexContent>
			<xsd:extension base="xsd:anyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:element name="textbox" type="dscsim:TextBoxType"></xsd:element>
	<xsd:element name="editbox" type="dscsim:EditBoxType"></xsd:element>
	<xsd:element name="menubox" type="dscsim:MenuType"></xsd:element>
	
	
	
	<xsd:complexType name="Actions">
		<xsd:sequence>
			<xsd:element name="action" type="dscsim:ActionMapping" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>				
	</xsd:complexType>

				
	<xsd:complexType name="ActionMapping">
		<xsd:complexContent>
			<xsd:restriction base="xsd:anyType">
				<xsd:attribute name="event" type="xsd:string"/>
				<xsd:attribute name="source" type="xsd:string"/>
				<xsd:attribute name="forward" type="xsd:string" use="required"/>		
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>
	
</xsd:schema>

=== asrulhadi/dscsim/src/main/resources/etc/ship-screens.xml
<?xml version="1.0" encoding="UTF-8"?>

<dscsim:device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:dscsim="http://dscsim.sourcefore.net/xml/ns/dscsim"
  xsi:schemaLocation="http://dscsim.sourcefore.net/xml/ns/dscsim D:\\Projekte\\sourceforge\\dscsim\\src\\main\\resources\\etc\\device.xsd">

	<dscsim:screens>
					
		<dscsim:screen name="welcome" implementation="net.sourceforge.dscsim.controller.display.screens.impl.JMainScreen">	
			<dscsim:fields>
				<dscsim:textbox row="0" column="1" width="20" height="1">-VHF DSC CONTROLLER-</dscsim:textbox>								
				<dscsim:textbox row="2" column="4" width="13" height="1">CH70 WATCHING</dscsim:textbox>
				<dscsim:textbox row="4" column="0" width="4" height="1" name="source"></dscsim:textbox>
				<dscsim:textbox row="4" column="5" width="15" height="1" name="time"></dscsim:textbox>					
				<dscsim:textbox row="5" column="5" width="16" height="1" name="lat"></dscsim:textbox>
				<dscsim:textbox row="6" column="5" width="15" height="1" name="lon"></dscsim:textbox>
			</dscsim:fields>
			
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_CALL" forward="main_entry_screen"/>
			</dscsim:actions>
		</dscsim:screen>
			
		<dscsim:screen name="main_entry_screen"  implementation="net.sourceforge.dscsim.controller.display.screens.impl.MainMenuScreen" scope="session" >
			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Select a subject</dscsim:textbox>
				<dscsim:menubox name="main_menu" row="1" column="0" width="19" height="6">				
					<dscsim:choice  link="position_input">Entry position/time</dscsim:choice>
					<dscsim:choice  link="select_call_id" code="TYPE_INDIVIDUAL">Individual call</dscsim:choice>			
					<dscsim:choice  link="select_ack_individ" code="TYPE_INDIVIDUAL_ACK">Individual ACK</dscsim:choice>
					<dscsim:choice  link="select_group_id" code="TYPE_GROUP">Group call</dscsim:choice>
					<dscsim:choice  link="select_category" code="TYPE_ALL_SHIPS">All ship calls</dscsim:choice>			
					<dscsim:choice  link="system_not_implemented" code="TYPE_POSITION_REQ">Position request</dscsim:choice>
					<dscsim:choice  link="select_received_calls">Received calls</dscsim:choice>
					<dscsim:choice  link="select_distress_nature">Distress setting</dscsim:choice>
					<dscsim:choice  link="setup_menu">Set up</dscsim:choice>		
				</dscsim:menubox>	
				<dscsim:textbox row="7" column="2" width="15" height="1">Exit / ENT->OK</dscsim:textbox>
			</dscsim:fields>
		</dscsim:screen>
		
		<dscsim:screen name="position_input" implementation="net.sourceforge.dscsim.controller.display.screens.impl.JPositionEntryScreen">

			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Input a position</dscsim:textbox>				

				<dscsim:textbox row="1" column="1" width="9" height="1">Lattitude</dscsim:textbox>
				<dscsim:editbox row="2" column="3" width="2" height="1" name="latdeg"/>
				<dscsim:textbox row="2" column="6" width="1" height="1">째</dscsim:textbox>
				<dscsim:editbox row="2" column="8" width="2" height="1" name="latmin"/>
				<dscsim:textbox row="2" column="11" width="1" height="1">'</dscsim:textbox>
				<dscsim:editbox row="2" column="13" width="1" height="1" name="lathem" tabon="ENT"/>
				<dscsim:textbox row="2" column="15" width="4" height="1" name="latnull">Null</dscsim:textbox>
			
				<dscsim:textbox row="4" column="1" width="9" height="1">Longitude</dscsim:textbox>
				<dscsim:editbox row="5" column="2" width="3" height="1" name="londeg"/>
				<dscsim:textbox row="5" column="6" width="1" height="1">째</dscsim:textbox>
				<dscsim:editbox row="5" column="8" width="2" height="1" name="lonmin"/>
				<dscsim:textbox row="5" column="11" width="1" height="1">'</dscsim:textbox>
				<dscsim:editbox row="5" column="13" width="1" height="1" name="lonhem" tabon="ENT"/>
				<dscsim:textbox row="5" column="15" width="4" height="1" name="lonnull">Null</dscsim:textbox>

				<dscsim:textbox row="6" column="2" width="17" height="1">A/a->Null data</dscsim:textbox>
				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>
			</dscsim:fields>	
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_ENT" forward="time_input"/>
			</dscsim:actions>
		
		</dscsim:screen>	
		
		
		<dscsim:screen name="time_input" implementation="net.sourceforge.dscsim.controller.display.screens.impl.JTimeEntryScreen">

			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Input a Time</dscsim:textbox>				

				<dscsim:textbox row="2" column="1" width="3" height="1">UTC</dscsim:textbox>
				<dscsim:editbox row="2" column="5" width="2" height="1" name="hours"/>
				<dscsim:textbox row="2" column="7" width="1" height="1">:</dscsim:textbox>
				<dscsim:editbox row="2" column="8" width="2" height="1" name="minutes"/>
				<dscsim:textbox row="2" column="11" width="4" height="1" name="timenull">Null</dscsim:textbox>
			
				<dscsim:textbox row="6" column="2" width="17" height="1">A/a->Null data</dscsim:textbox>
				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>
			</dscsim:fields>	
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_ENT" forward="welcome"/>
			</dscsim:actions>
		
		</dscsim:screen>		
		
		<dscsim:screen name="select_call_id"  implementation="net.sourceforge.dscsim.controller.display.screens.impl.SelectAddressIdScreen" >

			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Select address ID</dscsim:textbox>
							
		 		<dscsim:menubox name="address_ids_list" row="1" column="0" width="19" height="6">				
					<dscsim:choice  link="enter_mmsi">Manual entry</dscsim:choice>		 		
		 		</dscsim:menubox>
		 		
		 		<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>	 		
			</dscsim:fields>
			
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_CLR" forward="main_entry_screen"/>
			</dscsim:actions>
			
		</dscsim:screen>
		
		<dscsim:screen name="enter_mmsi" implementation="net.sourceforge.dscsim.controller.display.screens.impl.EnterMmsiScreen">
			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Input an address</dscsim:textbox>
				<dscsim:textbox row="2" column="2" width="12" height="1">ID:(9 digit)</dscsim:textbox>			
				<dscsim:editbox row="3" column="6" width="9" height="1" name="mmsi_input"/>
				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>
			</dscsim:fields>	
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_ENT" forward="select_category"/>
				<dscsim:action event="PRSD" source="FK_CLR" forward="main_entry_screen"/>
			</dscsim:actions>
		</dscsim:screen>		
		
		<dscsim:screen name="select_category" implementation="net.sourceforge.dscsim.controller.display.screens.impl.SelectCatagoryScreen" scope="transient">
			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="17" height="1">Select a category</dscsim:textbox>
		 		<dscsim:menubox name="catagories" row="1" column="0" width="19" height="6">				
					<dscsim:choice link="channel_input" code="CAT_ROUTINE">Routine</dscsim:choice>	
					<dscsim:choice link="channel_input" code="CAT_SAFETY">Saftey</dscsim:choice>		 		
					<dscsim:choice link="channel_input" code="CAT_URGENCY">Urgency</dscsim:choice>		 		
					<dscsim:choice link="channel_input" code="CAT_DISTRESS">Distress</dscsim:choice>		 			 		
		 		</dscsim:menubox>
				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>	
			</dscsim:fields>										
		</dscsim:screen>
		
		
		<dscsim:screen name="channel_input" implementation="net.sourceforge.dscsim.controller.display.screens.impl.EnterChannelScreen" scope="transient">
			<dscsim:fields>
				<dscsim:textbox row="0" column="1" width="18" height="1">Input a traffic CH</dscsim:textbox>
				<dscsim:textbox row="3" column="2" width="3" height="1">CH:</dscsim:textbox>
				<dscsim:editbox row="3" column="6" width="2" height="1" name="channel"/>
				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>	
			</dscsim:fields>
			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_ENT" forward="individual_send"/>
				<dscsim:action event="PRSD" source="FK_CLR" forward="main_entry_screen"/>
			</dscsim:actions>				
		</dscsim:screen>
		
		<dscsim:screen name="individual_send" implementation="net.sourceforge.dscsim.controller.display.screens.impl.SendActionScreen">

			<dscsim:fields>
				<dscsim:textbox row="0" column="0" width="21" height="1">Push [CALL] and [ENT]</dscsim:textbox>
				<dscsim:textbox row="1" column="7" width="14" height="1">simultaneously</dscsim:textbox>
				<dscsim:textbox row="6" column="1" width="19" height="1">To stop the call,</dscsim:textbox>	
				<dscsim:textbox row="7" column="1" width="19" height="1">push [CLR]</dscsim:textbox>					
			</dscsim:fields>

			<dscsim:actions>
				<dscsim:action event="PRSD" source="FK_ENT" forward="welcome"/>
				<dscsim:action event="PRSD" source="FK_CLR" forward="main_entry_screen"/>
			</dscsim:actions>					

		</dscsim:screen>	
		
		<dscsim:screen name="select_received_calls" implementation="net.sourceforge.dscsim.controller.display.screens.framework.MenuScreen">
			<dscsim:description>Show protocal of received calls.</dscsim:description>
			<dscsim:fields>
				<dscsim:textbox row="0" column="2" width="16" height="1">Select a message</dscsim:textbox>				
	
				<dscsim:menubox name="call_type_menu" row="2" column="0" width="19" height="2">				
					<dscsim:choice  link="show_distress_calls">Distress message</dscsim:choice>
					<dscsim:choice  link="show_other_calls">Other message</dscsim:choice>			
				</dscsim:menubox>	

				<dscsim:textbox row="7" column="1" width="19" height="1">CLR->Exit / ENT->OK</dscsim:textbox>
			</dscsim:fields>
			<dscsim:actions>
